### ISSUE TITLE
CUDA OOM during ckpt saving for Llama2-70b

### ISSUE THREAD

**Issue by lwmlyy** [meta-llama/llama-recipes#142]
Hi, I am using 8*a100-80gb to lora-finetune Llama2-70b, the training and evaluation during epoch-1 went well, but went OOM when saving the peft model. The nightly version of pytorch is used.

The following command is used:
torchrun --nnodes 1 --nproc_per_node 8 llama_finetuning.py --enable_fsdp --low_cpu_fsdp --model_name ../Llama-2-70b-chat-hf --micro_batch_size 1 --batch_size_training 1 --dist_checkpoint_root_folder ../Llama-2-70b-chat-hf/ --dist_checkpoint_folder fine-tuned --use_peft --peft_method lora --lr 3e-4 --epoch 2 --pure_bf16 --alpaca_dataset --output_dir llama-70b-lorawallsft

"we are about to save the PEFT modules", it went CUDA OOM after this log is printed.

**Comment by clechristophe** [comment]
I have the same problem. I think everything is brought back to the first rank before saving and it causes CUDA OOM. I was able to save one .distcp file per GPU but I'm not sure how to get just the LoRA adapter file from there...

**Comment by gongy** [comment]
Any ideas on how to resolve this?

**Comment by jshin49** [comment]
Any updates on this issue? I'm encountering the same problem with 8 x A100 (80GB) for Lora 70B

**Comment by matthieumeeus** [comment]
I'm facing the same issue. Any workaround?

**Comment by gongy** [comment]
I found a workaround which involves allowing CPU offloading during the phase of saving the state dict.

I tested that end-to-end 70B training works with checkpointing on [this repo](https://github.com/modal-labs/llama-finetuning).

I will try to find the time to merge in the changes soon, but you can find them here https://github.com/modal-labs/llama-recipes

**Comment by JazzTheSaver** [comment]
I'm encountering the same problem with 6 x H800 (80GB) for Lora 70B

**Comment by yuanzhedong** [comment]
I'm encountering the same problem with 8 x H100 (80GB) for Lora 70B

**Comment by HamidShojanazeri** [comment]
sorry for the late reply @yuanzhedong and everyone, is this happening only alpaca? I believe some of the issue from Sep should be resolved. We have the[ CPU offload now](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/configs/fsdp.py#L19) if that can be helpful.

**Comment by HamidShojanazeri** [comment]
@yuanzhedong It seems like an issue with transformers, could repro this issue with transformers version of `4.38.1` which is from pip install, installing from src could resolve the issue `transformers    4.39.0.dev0 `

```
git clone https://github.com/huggingface/transformers.git
cd transformers/

pip install -e .

```

can you pls give it a try.

**Comment by Mugheeera** [comment]
@HamidShojanazeri Thank you very much for your reply. I tried with a new install of `transformers 4.39.0.dev0` from the src but still encountered with the same issue. I have also attempted to decrease the batch size but to no avail. I am using a custom dataset modelled after the structure of Alpaca dataset. I will now make some modifications to the dataset and proceed with a clean installation llama-recipes and see how it goes.

**Comment by HamidShojanazeri** [comment]
sure, it shouldn't have anything to do with your batch size, the version conflict was the only way I could repro and by pass it. Pls let know how it went.

**Comment by Mugheeera** [comment]
I tried with the following package versions and a fresh install of llama-recipes, but still getting the same error.

`accelerate 0.28.0, appdirs 1.4.4,  bitsandbytes 0.43.0, black 24.3.0, datasets 2.18.0, fire 0.6.0, gradio 4.22.0, gradio_client 0.13.0 loralib 0.1.2, matplotlib 3.8.3, matplotlib-inline 0.1.6 ,optimum 1.17.1, peft 0.9.0 ,py7zr 0.21.0, scipy 1.12.0, sentencepiece 0.2.0, torch 2.3.0+cu118, transformers  4.39.0.dev0 /home/mugheera/transformers`

Below is the command that I used to run start the finetuning job

`torchrun --nnodes 1 --nproc_per_node 4  finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name /home/mugheera/llama-hf/Llama-2-70b-chat-hf --pure_bf16 --output_dir /home/mugheera/PEFT/model --use_fast_kernels`

Training Epoch: 1/3, step 46/47 completed (loss: 0.15002813935279846): 100%|████████████████████████████████████████████████| 47/47 [34:52<00:00, 44.52s/it]
Training Epoch: 1/3, step 46/47 completed (loss: 0.17413900792598724): 100%|████████████████████████████████████████████████| 47/47 [35:40<00:00, 45.54s/it]
Training Epoch: 1/3, step 46/47 completed (loss: 0.1314418613910675): 100%|█████████████████████████████████████████████████| 47/47 [34:16<00:00, 43.75s/it]
Training Epoch: 1/3, step 46/47 completed (loss: 0.18022574484348297): 100%|████████████████████████████████████████████████| 47/47 [35:46<00:00, 45.68s/it]
Max CUDA memory allocated was 31 GB
Max CUDA memory reserved was 39 GB
Peak active CUDA memory was 31 GB
CUDA Malloc retries : 0
CPU Total Peak Memory consumed during the train (max): 153 GB
evaluating Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:08<00:00,  4.00s/it]
evaluating Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:08<00:00,  4.02s/it]
evaluating Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:08<00:00,  4.02s/it]
evaluating Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:08<00:00,  4.02s/it]
 eval_ppl=tensor(1.1495, device='cuda:0') eval_epoch_loss=tensor(0.1393, device='cuda:0')
we are about to save the PEFT modules
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/mugheera/new/llama-recipes/recipes/finetuning/finetuning.py", line 8, in <module>
[rank2]:     fire.Fire(main)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
[rank2]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank2]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
[rank2]:     component, remaining_args = _CallAndUpdateTrace(
[rank2]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank2]:     component = fn(*varargs, **kwargs)
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/new/llama-recipes/src/llama_recipes/finetuning.py", line 265, in main
[rank2]:     results = train(
[rank2]:               ^^^^^^
[rank2]:   File "/home/mugheera/new/llama-recipes/src/llama_recipes/utils/train_utils.py", line 187, in train
[rank2]:     model.save_pretrained(train_config.output_dir)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/peft/peft_model.py", line 215, in save_pretrained
[rank2]:     output_state_dict = get_peft_model_state_dict(
[rank2]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/peft/utils/save_and_load.py", line 71, in get_peft_model_state_dict
[rank2]:     state_dict = model.state_dict()
[rank2]:                  ^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1911, in state_dict
[rank2]:     module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1911, in state_dict
[rank2]:     module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1911, in state_dict
[rank2]:     module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
[rank2]:   [Previous line repeated 2 more times]
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1907, in state_dict
[rank2]:     hook(self, prefix, keep_vars)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 786, in _pre_state_dict_hook
[rank2]:     _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 307, in _full_pre_state_dict_hook
[rank2]:     _common_unshard_pre_state_dict_hook(
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 174, in _common_unshard_pre_state_dict_hook
[rank2]:     _enter_unshard_params_ctx(
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 138, in _enter_unshard_params_ctx
[rank2]:     fsdp_state._unshard_params_ctx[module].__enter__()
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/contextlib.py", line 137, in __enter__
[rank2]:     return next(self.gen)
[rank2]:            ^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 196, in _unshard_fsdp_state_params
[rank2]:     _unshard(state, handle, computation_stream, computation_stream)
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 299, in _unshard
[rank2]:     handle.unshard()
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_flat_param.py", line 1307, in unshard
[rank2]:     unsharded_flat_param = self._alloc_padded_unsharded_flat_param()
[rank2]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_flat_param.py", line 1334, in _alloc_padded_unsharded_flat_param
[rank2]:     _alloc_storage(unsharded_flat_param, flat_param._padded_unsharded_size)  # type: ignore[attr-defined]
[rank2]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/utils.py", line 168, in _alloc_storage
[rank2]:     tensor._typed_storage()._resize_(size.numel())
[rank2]:   File "/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/storage.py", line 972, in _resize_
[rank2]:     self._untyped_storage.resize_(size * self._element_size())
[rank2]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.60 GiB. GPU  has a total capacity of 79.15 GiB of which 989.31 MiB is free. Process 4076404 has 4.03 GiB memory in use. Including non-PyTorch memory, this process has 74.00 GiB memory in use. Of the allocated memory 70.11 GiB is allocated by PyTorch, and 1.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management

And the following error in another iteration

evaluating Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:41<00:00,  3.75s/it]
 eval_ppl=tensor(2.6441, device='cuda:0') eval_epoch_loss=tensor(0.9723, device='cuda:0')
we are about to save the PEFT modulested (loss: 1.2340718507766724):  19%|█████████▌                                         | 9/48 [06:16<28:13, 43.41s/it]
/home/mugheera/miniconda3/envs/llama-recipes/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py:348: UserWarning: Failed to clone() tensor with name base_model.model.model.layers.23.mlp.up_proj.weight on rank 2. This may mean that this state_dict entry could point to invalid memory regions after returning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of base_model.model.model.layers.23.mlp.up_proj.weight. Error: CUDA out of memory. Tried to allocate 448.00 MiB. GPU  has a total capacity of 79.15 GiB of which 313.31 MiB is free. Process 4076404 has 4.03 GiB memory in use. Including non-PyTorch memory, this process has 74.82 GiB memory in use. Of the allocated memory 72.29 GiB is allocated by PyTorch, and 175.13 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management

**Comment by HamidShojanazeri** [comment]
sounds to be stale issue, will close it for now but feel free to re-open is see same issues.

**Comment by yueyugua** [comment]
Hi @HamidShojanazeri , I also got the same OOM error when using 8xH100s. 
I'm using the transformer `'4.41.0.dev0'` and build the llama-recipes from the source. 
I observed this error will happen when training with 70B model (in my case, the llama3-70b) and it does not exist for llama 3 8B. 
I'm wondering the reason to use use `model.save_pretrained` when using both PEFT and FSDP instead of using `save_model_and_optimizer_sharded` as did when not using PEFT? (https://github.com/meta-llama/llama-recipes/blob/c1f8de216740712eb0ed21f092c9fb9f47fd74ed/src/llama_recipes/utils/train_utils.py#L228-L259)
Would it possible the reason of OOM is because the model needs to gather weights across ranks before `model.save_pretrained`?

**Comment by Lidongw** [comment]
Hi @HamidShojanazeri I think you were testing with 7B model, most of the people here seeing the issue with 70B model. I also had the same issue with 70B model with alpaca dataset. I have installed llama-recipes from src, but still not working
